# Generated by Django 6.0 on 2025-12-18 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='column',
            unique_together=set(),
        ),
    ]
